const articles = [
  ['nte-pc-beginner-guide','Guides','NTE',"NTE on PC: A Beginner's Guide to Building a Clean First Session",'A practical starting point for smooth first sessions, sensible settings, and a setup that stays easy to tune.'],
  ['star-trek-fleet-command-pc-guide','Guides','Star Trek Fleet Command','Star Trek Fleet Command on PC: A Smarter Early-Game Route','Use your first hours well with a simple PC-first approach to missions, upgrades, resources, and a calmer daily loop.'],
  ['raid-shadow-legends-pc-progression-guide','Guides','Raid: Shadow Legends','Raid: Shadow Legends on PC: A No-Waste Progression Guide','Build a reliable early roster, avoid scattered upgrades, and use the PC client to make the daily grind easier.'],
  ['nte-pc-launch-watch','News','NTE','NTE PC Launch Watch: Your Pre-Download Checklist','The practical checklist for PC players tracking platform, storage, performance expectations, and account setup.'],
  ['star-trek-fleet-command-pc-update','News','Star Trek Fleet Command','Star Trek Fleet Command on PC: The Update Notes Worth Your Time','A player-first way to read new updates without losing the changes that affect daily PC play.'],
  ['raid-shadow-legends-pc-roundup','News','Raid: Shadow Legends','Raid: Shadow Legends PC Roundup: Events, Value, and What to Skip','A clear way to sort weekly activity on PC: what fits your roster and what can wait.'],
  ['nte-pc-first-impressions','Reviews','NTE','NTE on PC Review: A Promising First Look With Work to Do','An early PC verdict focused on presentation, controls, performance, and whether the first session earns a return visit.'],
  ['star-trek-fleet-command-pc-review','Reviews','Star Trek Fleet Command','Star Trek Fleet Command on PC Review: A Patient Strategy Loop','A measured review covering its long-term loop, interface comfort, and free-to-play pressure.'],
  ['raid-shadow-legends-pc-review','Reviews','Raid: Shadow Legends','Raid: Shadow Legends on PC Review: Strong Presentation, Heavy Grind','A polished roster builder with a satisfying core, but time and spending pressure deserve an honest verdict.'],
  ['best-budget-gaming-pc-upgrade-order','Setup','Gaming PC','The Best Upgrade Order for a Budget Gaming PC','A practical way to decide what to upgrade first when your gaming PC budget is limited.'],
  ['quiet-gaming-pc-setup','Setup','Gaming PC','How to Build a Quieter Gaming PC Setup','Reduce distracting noise with sensible fan curves, clean airflow, better placement, and patience.'],
  ['pc-settings-for-high-refresh-gaming','Setup','Gaming PC','High-Refresh PC Gaming Setup: Settings That Actually Matter','A clean checklist covering display mode, frame caps, latency, and motion clarity.']
];
const esc = s => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gameImages = { 'NTE':'nte-official-promo.png', 'Star Trek Fleet Command':'gamerzeta-stfc.png', 'Raid: Shadow Legends':'gamerzeta-raid.png' }; const articleImages = { 'nte-pc-beginner-guide':'gamerzeta-nte.png', 'star-trek-fleet-command-pc-guide':'gamerzeta-stfc.png', 'raid-shadow-legends-pc-progression-guide':'gamerzeta-raid.png', 'nte-pc-launch-watch':'nte-official-promo.png', 'star-trek-fleet-command-pc-update':'gamerzeta-hero.png', 'raid-shadow-legends-pc-roundup':'gamerzeta-setup.png', 'nte-pc-first-impressions':'share_en.jpg', 'star-trek-fleet-command-pc-review':'gamerzeta-guides.png', 'raid-shadow-legends-pc-review':'gamerzeta-hero.png', 'best-budget-gaming-pc-upgrade-order':'gamerzeta-setup.png', 'quiet-gaming-pc-setup':'gamerzeta-guides.png', 'pc-settings-for-high-refresh-gaming':'gamerzeta-stfc.png' };
const card = a => `<article class="card"><div class="thumb" style="background-image:linear-gradient(135deg,rgba(8,11,20,.18),rgba(92,124,250,.72)),url('${articleImages[a[0]] || gameImages[a[2]] || 'gamerzeta-guides.png'}')"><span class="mono">${a[1].toUpperCase()} · ${esc(a[2])}</span></div><div class="card-body"><div class="meta"><span>GAMERZETA</span><span>06 MIN READ</span></div><h3><a href="article.html?slug=${a[0]}">${esc(a[3])}</a></h3><p>${esc(a[4])}</p></div></article>`;
const qs = new URLSearchParams(location.search); const category = qs.get('category'); const slug = qs.get('slug');
if (document.body.dataset.page === 'category') { const cat = category ? category[0].toUpperCase()+category.slice(1) : 'Guides'; document.title = `${cat} — Gamerzeta`; document.querySelector('[data-title]').textContent=cat; document.querySelector('[data-dek]').textContent=`${cat} coverage for PC players: useful, current, and easy to act on.`; document.querySelector('[data-grid]').innerHTML=articles.filter(a=>a[1]===cat).map(card).join(''); }
if (document.body.dataset.page === 'article') { const a=articles.find(x=>x[0]===slug)||articles[0]; document.title=`${a[3]} — Gamerzeta`; document.querySelector('[data-category]').textContent=a[1].toUpperCase(); document.querySelector('[data-game]').textContent=a[2]; document.querySelector('[data-title]').textContent=a[3]; document.querySelector('[data-dek]').textContent=a[4]; document.querySelector('.article-cover').style.backgroundImage=`linear-gradient(135deg,rgba(8,11,20,.1),rgba(8,11,20,.35)),url('${articleImages[a[0]] || gameImages[a[2]] || 'gamerzeta-hero.png'}')`; document.querySelector('[data-body]').innerHTML=`<p>${esc(a[4])}</p><h2>What to check first</h2><p>Start with a stable PC baseline: confirm the platform requirements, choose a readable display mode, and make one change at a time. This keeps performance, comfort, and progression decisions easy to judge.</p><h2>The practical route</h2><p>Prioritize the next useful milestone instead of trying to optimize everything at once. Track the settings, upgrades, or in-game choices that affect your session, then build from evidence rather than hype.</p><h2>Who this is for</h2><p>This coverage is for PC players who want a clear starting point, a calmer way to compare options, and enough context to decide whether a game or setup deserves more time.</p><h2>Gamerzeta verdict</h2><p>This is the Gamerzeta standard: direct, practical, and written for players who want better sessions without the noise.</p>`; const anchor=document.getElementById('anchorAd'); if(anchor) window.addEventListener('scroll',()=>{if(window.scrollY>300) anchor.classList.add('is-visible')},{passive:true}); }
if (document.body.dataset.page === 'article') { const meta=document.querySelector('.article-meta'); if(meta) meta.insertAdjacentHTML('afterend','<div class="ad-slot ad-rectangle article-hero-ad" aria-label="Advertisement"><span class="mono">ADVERTISEMENT</span><strong>300 × 250</strong></div>'); }
const campaignVideo=document.querySelector('.campaign-media video'); if(campaignVideo){ campaignVideo.muted=true; campaignVideo.play().catch(()=>{}); }
if (document.body.dataset.page === 'article' && slug === 'star-trek-fleet-command-pc-guide') { const title='Star Trek Fleet Command on PC: Build Your First Fleet'; const dek='A practical early-game route for missions, research, upgrades, and a calmer daily loop on PC.'; document.title=`${title} — Gamerzeta`; document.querySelector('[data-title]').textContent=title; document.querySelector('[data-dek]').textContent=dek; document.querySelector('[data-body]').innerHTML=`<p>${dek}</p><h2>Choose one clear daily objective</h2><p>The early game can feel busy because every mission looks urgent. Pick one main goal for the day—unlocking a system, improving a ship, or moving a research branch forward—and let your smaller tasks support it.</p><h2>Build your economy before chasing power</h2><p>Prioritize upgrades that unlock new options or reduce repeat work. Keep a simple reserve of key resources so one timer or event does not force you to stop your main progression.</p><h2>Use your fleet as a system</h2><p>Think about ship roles, crew bonuses, repair time, and mission requirements together. A balanced early fleet is more useful than one expensive ship that cannot cover your next objective.</p><h2>Make the PC client work for you</h2><p>Use a readable window size, a short checklist, and a consistent routine. The larger screen makes it easier to compare missions, manage timers, and plan upgrades without rushing.</p><h2>Gamerzeta takeaway</h2><p>Star Trek Fleet Command is at its best when you treat progression as a sequence of small decisions. Build steadily, protect your resources, and let your next unlock guide the plan.</p>`; }
if (document.body.dataset.page === 'article' && slug === 'raid-shadow-legends-pc-review') { const title='Raid: Shadow Legends on PC: Great Core, Heavy Grind'; const dek='Our honest PC review of Raid: Shadow Legends, covering roster building, daily time, events, and spending pressure.'; document.title=`${title} — Gamerzeta`; document.querySelector('[data-title]').textContent=title; document.querySelector('[data-dek]').textContent=dek; document.querySelector('[data-body]').innerHTML=`<p>${dek}</p><h2>The team-building loop is the hook</h2><p>Raid is strongest when a new champion changes how you approach a stage. Comparing roles, skills, gear, and turn order gives the core battles a satisfying layer of planning.</p><h2>PC makes the routine easier</h2><p>The PC client is comfortable for roster management, inventory cleanup, and longer planning sessions. A larger display helps you compare stats and make upgrades without rushing through menus.</p><h2>The grind needs an honest warning</h2><p>Progress depends on repetition, energy, timers, and resource choices. Set a clear session goal before you start so daily tasks do not quietly take over your play time.</p><h2>Events and offers require discipline</h2><p>Events can give your roster direction, but not every offer fits your account. Check the reward, the time required, and the next useful milestone before spending.</p><h2>Gamerzeta verdict</h2><p>Raid delivers a polished collection RPG with a rewarding strategic core. It is worth trying on PC if you enjoy long-term roster building, but it is best experienced with firm limits on time and spending.</p>`; }
if (document.body.dataset.page === 'article') { const main=document.querySelector('.article-page'); main.insertAdjacentHTML('afterbegin','<div class="ad-band"><div class="ad-slot ad-leaderboard" aria-label="Advertisement"><span class="mono">ADVERTISEMENT</span><strong>728 × 90</strong></div></div>'); const anchor=document.createElement('div'); anchor.className='ad-anchor'; anchor.innerHTML='<span class="mono">ADVERTISEMENT · 728 × 90</span><button type="button" aria-label="Close ad">×</button>'; anchor.querySelector('button').onclick=()=>anchor.remove(); main.appendChild(anchor); window.addEventListener('scroll',()=>{if(window.scrollY>300) anchor.classList.add('is-visible')},{passive:true}); }
