(function(){
  const data=[
    ['nte-pc-beginner-guide','Guides','NTE',"NTE on PC: A Beginner's Guide to Building a Clean First Session",'A practical starting point for smooth first sessions, sensible settings, and a setup that stays easy to tune.','affiliate-assets/nte-hero-clean.jpg'],
    ['star-trek-fleet-command-pc-guide','Guides','Star Trek Fleet Command','Star Trek Fleet Command Beginner Guide: What to Upgrade First','A practical early-game route for your station, ships, officers, research, and daily resources on PC.','affiliate-assets/star-trek-affiliate-clean.jpg'],
    ['raid-shadow-legends-pc-progression-guide','Guides','Raid: Shadow Legends','Raid: Shadow Legends Beginner Guide: A No-Waste PC Route','Build one reliable early team, protect scarce resources, and use the PC version to simplify progression.','affiliate-assets/raid-affiliate-clean.jpg'],
    ['nte-pc-launch-watch','Guides','Neverness to Everness','NTE PC Requirements and Best Settings: What Your PC Needs','Official NTE PC requirements, storage advice, and a practical settings order for smoother performance.','creative/nte-poster.jfif'],
    ['star-trek-fleet-command-pc-update','News','Star Trek Fleet Command','Star Trek Fleet Command on PC: The Update Notes Worth Your Time','A player-first way to read new updates without losing the changes that affect daily PC play.','gamerzeta-hero.png'],
    ['raid-shadow-legends-pc-roundup','News','Raid: Shadow Legends','Raid: Shadow Legends PC Roundup: Events, Value, and What to Skip','A clear way to sort weekly activity on PC: what fits your roster and what can wait.','gamerzeta-setup.png'],
    ['nte-pc-first-impressions','Reviews','NTE','NTE on PC Review: A Promising First Look With Work to Do','An early PC verdict focused on presentation, controls, performance, and whether the first session earns a return visit.','affiliate-assets/nte-article-clean.jpg'],
    ['star-trek-fleet-command-pc-review','Reviews','Star Trek Fleet Command','Star Trek Fleet Command on PC Review: A Patient Strategy Loop','A measured review covering its long-term loop, interface comfort, and free-to-play pressure.','gamerzeta-guides.png'],
    ['raid-shadow-legends-pc-review','Reviews','Raid: Shadow Legends','Raid: Shadow Legends on PC Review: Strong Presentation, Heavy Grind','A polished roster builder with a satisfying core, but time and spending pressure deserve an honest verdict.','gamerzeta-hero.png'],
    ['best-budget-gaming-pc-upgrade-order','Setup','Gaming PC','Best Budget Gaming PC Upgrade Order: Where to Spend First','Find the real bottleneck and spend your upgrade budget where it will make the biggest difference.','gamerzeta-setup.png'],
    ['quiet-gaming-pc-setup','Setup','Gaming PC','How to Build a Quieter Gaming PC Setup','Reduce noise with cleaner airflow, measured fan curves, sensible power limits, and focused upgrades.','gamerzeta-guides.png'],
    ['pc-settings-for-high-refresh-gaming','Setup','Gaming PC','Best PC Settings for High-Refresh Gaming','Configure refresh rate, adaptive sync, frame caps, latency settings, and graphics options for smoother gaming.','gamerzeta-stfc.png']
  ];
  const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const card=a=>`<article class="card"><div class="thumb" style="background-image:linear-gradient(135deg,rgba(8,11,20,.18),rgba(92,124,250,.72)),url('${a[5]}')"><span class="mono">${esc(a[1].toUpperCase())} · ${esc(a[2])}</span></div><div class="card-body"><div class="meta"><span>GAMERZETA</span><span>06 MIN READ</span></div><h3><a href="article.html?slug=${a[0]}">${esc(a[3])}</a></h3><p>${esc(a[4])}</p></div></article>`;
  document.querySelectorAll('nav').forEach(n=>{if(!n.querySelector('a[href="archive.html"]'))n.insertAdjacentHTML('beforeend','<a href="archive.html">Archive</a>')});
  document.querySelectorAll('.section-head').forEach(h=>{if(h.textContent.includes('All coverage')){const s=h.querySelector('span');if(s)s.outerHTML='<a class="mono" href="archive.html">All coverage →</a>'}});
  if(document.body.dataset.page==='home'){const m=document.querySelector('.campaign-media');if(m&&!m.querySelector('video'))m.innerHTML='<video class="campaign-video" controls muted loop playsinline preload="metadata" poster="creative/nte-poster.jfif"><source src="creative/nte-campaign.mp4" type="video/mp4"><img src="creative/nte-poster.jfif" alt="Neverness to Everness campaign artwork"></video><span class="mono campaign-caption">NTE / IMAGE 2026 CREATIVE</span>'}
  if(document.body.dataset.page==='archive'){const g=document.querySelector('[data-archive-grid]'),q=document.querySelector('[data-archive-search]'),c=document.querySelector('[data-archive-count]'),e=document.querySelector('[data-archive-empty]');let f='All';const render=()=>{const t=(q.value||'').toLowerCase().trim(),m=data.filter(a=>(f==='All'||a[1]===f)&&(!t||a.slice(1,5).join(' ').toLowerCase().includes(t)));g.innerHTML=m.map(card).join('');c.textContent=m.length+' article'+(m.length===1?'':'s');e.hidden=m.length>0};document.querySelectorAll('[data-archive-filter]').forEach(b=>b.addEventListener('click',()=>{f=b.dataset.archiveFilter;document.querySelectorAll('[data-archive-filter]').forEach(x=>x.classList.toggle('is-active',x===b));render()}));q.addEventListener('input',render);render()}
})();
