(function(){
  const data=[
    ['nte-pc-beginner-guide','Guides','NTE',"NTE on PC: A Beginner's Guide to Building a Clean First Session",'A practical starting point for smooth first sessions, sensible settings, and a setup that stays easy to tune.','affiliate-assets/nte-hero-clean.jpg'],
    ['star-trek-fleet-command-pc-guide','Guides','Star Trek Fleet Command','Star Trek Fleet Command Beginner Guide: What to Upgrade First','A practical early-game route for your station, ships, officers, research, and daily resources on PC.','affiliate-assets/star-trek-affiliate-clean.jpg'],
    ['raid-shadow-legends-pc-progression-guide','Guides','Raid: Shadow Legends','Raid: Shadow Legends Beginner Guide: A No-Waste PC Route','Build one reliable early team, protect scarce resources, and use the PC version to simplify progression.','affiliate-assets/raid-affiliate-clean.jpg'],
    ['nte-pc-launch-watch','Guides','Neverness to Everness','NTE PC Requirements and Best Settings: What Your PC Needs','Official NTE PC requirements, storage advice, and a practical settings order for smoother performance.','creative/nte-poster.jfif'],
    ['star-trek-fleet-command-pc-update','News','Star Trek Fleet Command','Star Trek Fleet Command on PC: The Update Notes Worth Your Time','A player-first way to read new updates without losing the changes that affect daily PC play.','gamerzeta-hero.png'],
    ['raid-shadow-legends-pc-roundup','News','Raid: Shadow Legends','Raid: Shadow Legends PC Roundup: Events, Value, and What to Skip','A clear way to sort weekly activity on PC: what fits your roster and what can wait.','gamerzeta-setup.png'],
    ['nte-pc-first-impressions','Reviews','NTE','NTE on PC Review: A Promising First Look With Work to Do','An early PC verdict focused on presentation, controls, performance, and whether the first session earns a return visit.','affiliate-assets/nte-article-clean.jpg'],
    ['star-trek-fleet-command-pc-review','Reviews','Star Trek Fleet Command','Star Trek Fleet Command on PC Review: A Patient Strategy Loop','A measured review covering its long-term loop, interface comfort, and free-to-play pressure.','gamerzeta-guides.png'],
    ['raid-shadow-legends-pc-review','Reviews','Raid: Shadow Legends','Raid: Shadow Legends on PC Review: Strong Presentation, Heavy Grind','A polished roster builder with a satisfying core, but time and spending pressure deserve an honest verdict.','gamerzeta-hero.png'],
    ['best-budget-gaming-pc-upgrade-order','Setup','Gaming PC','Best Budget Gaming PC Upgrade Order: Where to Spend First','Find the real bottleneck and spend your upgrade budget where it will make the biggest difference.','gamerzeta-setup.png'],
    ['quiet-gaming-pc-setup','Setup','Gaming PC','How to Build a Quieter Gaming PC Setup','Reduce noise with cleaner airflow, measured fan curves, sensible power limits, and focused upgrades.','gamerzeta-guides.png'],
    ['pc-settings-for-high-refresh-gaming','Setup','Gaming PC','Best PC Settings for High-Refresh Gaming','Configure refresh rate, adaptive sync, frame caps, latency settings, and graphics options for smoother gaming.','gamerzeta-stfc.png']
  ];
  const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const card=a=>`<article class="card"><div class="thumb" style="background-image:linear-gradient(135deg,rgba(8,11,20,.18),rgba(92,124,250,.72)),url('${a[5]}')"><span class="mono">${esc(a[1].toUpperCase())} · ${esc(a[2])}</span></div><div class="card-body"><div class="meta"><span>GAMERZETA</span><span>06 MIN READ</span></div><h3><a href="article.html?slug=${a[0]}">${esc(a[3])}</a></h3><p>${esc(a[4])}</p></div></article>`;
  document.querySelectorAll('nav').forEach(n=>{if(!n.querySelector('a[href="archive.html"]'))n.insertAdjacentHTML('beforeend','<a href="archive.html">Archive</a>')});
  document.querySelectorAll('.section-head').forEach(h=>{if(h.textContent.includes('All coverage')){const s=h.querySelector('span');if(s)s.outerHTML='<a class="mono" href="archive.html">All coverage →</a>'}});
  if(document.body.dataset.page==='category'){const title=document.querySelector('[data-title]')?.textContent.trim().toLowerCase();if(title==='guides'){document.querySelectorAll('.section-head,[data-grid]').forEach(x=>x.remove());const main=document.querySelector('main');const dek=document.querySelector('[data-dek]');if(dek)dek.textContent='Step-by-step gaming PC and game guides for better decisions, smoother sessions, and faster progress.';if(main&&!document.querySelector('.ad-band'))main.insertAdjacentHTML('afterbegin','<div class="ad-band"><a class="ad-creative" href="article.html?slug=nte-pc-launch-watch" aria-label="Read Gamerzeta NTE PC coverage"><img class="ad-slide ad-slide-a" src="gamerzeta-nte.png" alt="Neverness to Everness gaming artwork"><span class="ad-copy mono">NEVERNESS TO EVERNESS / PLAY FREE</span><span class="ad-cta">READ THE NTE GUIDE</span></a></div>');const hero=document.querySelector('.hero');if(hero&&!document.querySelector('.ad-rail'))hero.insertAdjacentHTML('afterend','<div class="ad-rail" aria-label="Advertisement"><div class="ad-slot ad-rectangle" aria-label="Advertisement"><span class="mono">ADVERTISEMENT</span><strong>300 × 250</strong></div><div class="ad-slot ad-sky" aria-label="Advertisement"><span class="mono">ADVERTISEMENT</span><strong>120 × 600</strong></div></div>');if(hero&&!document.querySelector('.guides-start'))hero.insertAdjacentHTML('afterend','<section class="guides-start"><div class="section-head"><div><span class="mono">GAMERZETA START HERE</span><h2>Choose your next move</h2></div><span class="mono">THREE CLEAR ROUTES</span></div><div class="guides-note"><p>Use the archive to follow the route that fits your session: tune the gaming PC, start Neverness to Everness, or build smarter habits in Star Trek Fleet Command and RAID: Shadow Legends.</p><a class="mono" href="archive.html">Browse the complete guide archive →</a></div></section>')}else{const h=[...document.querySelectorAll('.section-head')].find(x=>x.textContent.includes('Latest coverage'));if(h)h.remove()}}
  if(document.body.dataset.page==='category'&&document.querySelector('[data-title]')?.textContent.trim().toLowerCase()==='guides'){document.querySelectorAll('.guides-start,.guide-routes,.guide-route,.guides-note').forEach(x=>x.remove());const hero=document.querySelector('.hero'),band=document.querySelector('.ad-band');if(hero&&band)band.after(hero)}
  if(document.body.dataset.page==='home'){const m=document.querySelector('.campaign-media');if(m&&m.querySelector('video'))m.innerHTML='<img src="nte-official-promo.png" width="596" height="336" alt="Neverness to Everness promotional campaign artwork" loading="lazy"><img src="share_en.jpg" width="596" height="336" alt="Neverness to Everness campaign artwork" loading="lazy">'}
  if(document.body.dataset.page==='archive'){const g=document.querySelector('[data-archive-grid]'),q=document.querySelector('[data-archive-search]'),c=document.querySelector('[data-archive-count]'),e=document.querySelector('[data-archive-empty]');let f='All';const desks=['Gaming PC','Neverness to Everness','Star Trek Fleet Command','Raid: Shadow Legends'];const render=()=>{const t=(q.value||'').toLowerCase().trim(),m=data.filter(a=>(f==='All'||a[1]===f)&&(!t||a.slice(1,5).join(' ').toLowerCase().includes(t)));g.innerHTML='';g.classList.add('archive-results-hidden');const wrap=document.querySelector('.archive-desks')||document.createElement('div');wrap.className='archive-desks';if(!wrap.parentNode)g.parentNode.insertBefore(wrap,g);wrap.innerHTML='';const groups=desks.map(d=>[d,m.filter(a=>a[2]===d)]).filter(x=>x[1].length);if(f!=='All'&&t==='')groups.length=0;const shownGroups=f!=='All'&&!t?[[f,m]]:groups;shownGroups.forEach(([desk,items])=>{const sec=document.createElement('section');sec.className='archive-desk';sec.innerHTML='<div class="archive-desk-head"><div><span class="mono">GAMERZETA DESK</span><h2>'+esc(desk)+'</h2></div><span class="mono">'+items.length+' article'+(items.length===1?'':'s')+'</span></div><div class="cards archive-desk-grid">'+items.map(card).join('')+'</div>';wrap.appendChild(sec)});c.textContent=m.length+' article'+(m.length===1?'':'s')+' · '+shownGroups.length+' desk'+(shownGroups.length===1?'':'s');e.hidden=m.length>0};document.querySelectorAll('[data-archive-filter]').forEach(b=>b.addEventListener('click',()=>{f=b.dataset.archiveFilter;document.querySelectorAll('[data-archive-filter]').forEach(x=>x.classList.toggle('is-active',x===b));render()}));q.addEventListener('input',render);render()}
})();
